In [63]:
import numpy as np

In [64]:
import importlib
import doctest

# Pointwise norm-2 for v and w

In [71]:
import pointwise_norm_2
importlib.reload(pointwise_norm_2)
pointwise_norm_2_doctest_result = doctest.testmod(pointwise_norm_2)
print(pointwise_norm_2_doctest_result)
assert pointwise_norm_2_doctest_result.failed == 0, f"result.failed={pointwise_norm_2_doctest_result.failed}"

All test cases for pointwise_norm_2_v passed.
All test cases for pointwise_norm_2_w passed.
test_against_explicit : All tests pass
TestResults(failed=0, attempted=16)


In [72]:
from pointwise_norm_2 import test_against_explicit
test_against_explicit()

test_against_explicit : All tests pass


# Project alpha_1 and alpha_0

In [73]:
import projection_op
importlib.reload(projection_op)
projection_op_doctest_result = doctest.testmod(projection_op)
print(projection_op_doctest_result)
assert projection_op_doctest_result.failed == 0, f"result.failed={projection_op_doctest_result.failed}"

**********************************************************************
File "/mnt/h/GIT/DISSERTATION/LearningRegularizationParameterMaps/networks/drafts/projection_op.py", line 72, in projection_op.P_alpha0_w
Failed example:
    np.round(P_alpha0_w(w, alpha0), 2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest projection_op.P_alpha0_w[2]>", line 1, in <module>
        np.round(P_alpha0_w(w, alpha0), 2)
      File "/mnt/h/GIT/DISSERTATION/LearningRegularizationParameterMaps/networks/drafts/projection_op.py", line 119, in P_alpha0_w
        factor = np.max(1, max_over_alpha0)
      File "<__array_function__ internals>", line 180, in amax
      File "/mnt/h/GIT/DISSERTATION/LearningRegularizationParameterMaps/venv_2/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2793, in amax
        return _wrapreduction(a, np.maximum, 'max

AssertionError: result.failed=4

# Finite difference

In [68]:
import finite_diff
importlib.reload(finite_diff)

<module 'finite_diff' from '/mnt/h/GIT/DISSERTATION/LearningRegularizationParameterMaps/networks/drafts/finite_diff.py'>

# Grad op - Nabla_h and E_h

In [69]:
import grad_op
importlib.reload(grad_op)

<module 'grad_op' from '/mnt/h/GIT/DISSERTATION/LearningRegularizationParameterMaps/networks/drafts/grad_op.py'>

In [70]:
# import numpy as np

# def pointwise_norm_2_v(v):
#     """
#     Calculate the pointwise L2 norm for v.

#     Parameters:
#     v (numpy.ndarray): A numpy array of shape (n, n, 2)

#     Returns:
#     numpy.ndarray: A numpy array of shape (n, n) representing the pointwise L2 norm of v.

#     Examples:
#     >>> v = np.array([
#     ...     [[3, 4], [1, 2], [5, 12]],
#     ...     [[7, 24], [6, 8], [2, 3]],
#     ...     [[8, 15], [9, 12], [5, 12]]
#     ... ])
#     >>> pointwise_norm_2_v(v)
#     array([[ 5.        ,  2.23606798, 13.        ],
#            [25.        , 10.        ,  3.60555128],
#            [17.        , 15.        , 13.        ]])

#     >>> v = np.array([
#     ...     [[1, 0], [0, 1], [3, 4]],
#     ...     [[4, 3], [5, 12], [6, 8]],
#     ...     [[8, 6], [7, 24], [9, 12]]
#     ... ])
#     >>> pointwise_norm_2_v(v)
#     array([[ 1.,  1.,  5.],
#            [ 5., 13., 10.],
#            [10., 25., 15.]])
#     """
#     n = v.shape[0]
#     magnitude_v = np.zeros((n, n))
    
#     for i in range(n):
#         for j in range(n):
#             v1 = v[i, j, 0]
#             v2 = v[i, j, 1]
#             magnitude_v[i, j] = np.sqrt(v1**2 + v2**2)
    
#     return magnitude_v

# def pointwise_norm_2_w(w):
#     """
#     Calculate the pointwise L2 norm for w.

#     Parameters:
#     w (numpy.ndarray): A numpy array of shape (n, n, 2, 2)

#     Returns:
#     numpy.ndarray: A numpy array of shape (n, n) representing the pointwise L2 norm of w.

#     Examples:
#     >>> w = np.array([
#     ...     [[[3, 4], [4, 5]], [[6, 8], [8, 9]], [[1, 2], [2, 3]]],
#     ...     [[[7, 24], [24, 6]], [[8, 15], [15, 7]], [[9, 1], [1, 8]]],
#     ...     [[[4, 3], [3, 5]], [[2, 2], [2, 4]], [[6, 8], [8, 7]]]
#     ... ])
#     >>> pointwise_norm_2_w(w)
#     array([[ 8.1240384 , 15.65247584,  4.24264069],
#            [35.17101079, 23.72762104, 12.12435565],
#            [ 7.68114575,  5.29150262, 14.59451952]])

#     >>> w = np.array([
#     ...     [[[1, 0], [0, 2]], [[2, 0], [0, 3]], [[3, 0], [0, 4]]],
#     ...     [[[4, 0], [0, 5]], [[5, 0], [0, 6]], [[6, 0], [0, 7]]],
#     ...     [[[7, 0], [0, 8]], [[8, 0], [0, 9]], [[9, 0], [0, 10]]]
#     ... ])
#     >>> pointwise_norm_2_w(w)
#     array([[ 2.23606798,  3.60555128,  5.        ],
#            [ 6.40312424,  7.81024968,  9.21954446],
#            [10.63014581, 12.04159458, 13.45362405]])
#     """
#     n = w.shape[0]
#     magnitude_w = np.zeros((n, n))
    
#     for i in range(n):
#         for j in range(n):
#             w11 = w[i, j, 0, 0]
#             w22 = w[i, j, 1, 1]
#             w12 = w[i, j, 0, 1]
#             magnitude_w[i, j] = np.sqrt(w11**2 + w22**2 + 2 * w12**2)
    
#     return magnitude_w

# import doctest
# doctest.testmod()
