In [10]:
# Calculate singular value decomposition of a matrix
mat = [
    [-1, 1, 0, 0],
    [0, -1, 1, 0],
    [0, 0, -1, 1],
    [1, 0, 0, -1],
]

# Make a larger matrix similar to this but 256 by 256
# The diagonal should be (-1, 1), (-1, 1), (-1, 1), (-1, 1), ...
# The rest of the matrix should be zeros

# mat = np.zeros((256, 256))
# for i in range(256):
#     mat[i, i] = -1
#     mat[i, (i + 1) % 256] = 1

len = 4
# len = 512
mat = np.zeros((len * 3, len))
for i in range(len):
    mat[i, i] = 1
for i in range(len):
    mat[i + len, i] = -1
    # mat[i + len, (i + 1) % len] = 1
    mat[(i + 1) % len + len, i] = 1
for i in range(len):
    mat[i + len * 2, i] = -1
    # mat[(i + 1) % len + len * 2, i] = 1
    mat[i + len * 2, (i + 1) % len] = 1
    
    
    
print(f"Matrix of size {len * 2} by {len}:")
print(mat)
print()

# Find norm-1 of the matrix
print("Norm-1 of the matrix:")
print(np.linalg.norm(mat, 1))
print()

print("Norm-2 of the matrix:")
print(np.linalg.norm(mat, 2))
print()


import numpy as np
u, s, vh = np.linalg.svd(mat)

print("U:")
print(u)
print()

print("S:")
print(s)
print()

print("VH:")
print(vh)
print()

print("Reconstructed matrix:")
print(u @ np.diag(s) @ vh)
print()



Matrix of size 8 by 4:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1.  0.  0.  1.]
 [ 1. -1.  0.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  1. -1.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]
 [ 1.  0.  0. -1.]]

Norm-1 of the matrix:
5.0

Norm-2 of the matrix:
3.0

U:
[[-1.66666667e-01  3.16227766e-01  8.40323465e-17  5.00000000e-01
   3.77748177e-01 -4.06386577e-01 -2.34782680e-02  5.21166684e-02
   4.06386577e-01  2.34782680e-02 -5.21166684e-02 -3.77748177e-01]
 [ 1.66666667e-01  1.94506464e-17  3.16227766e-01  5.00000000e-01
   6.98678919e-02  3.61068393e-01 -4.19191195e-01 -1.17450899e-02
  -3.61068393e-01  4.19191195e-01  1.17450899e-02 -6.98678919e-02]
 [-1.66666667e-01 -3.16227766e-01  1.57029575e-18  5.00000000e-01
  -4.59705219e-02  1.02337457e-01  3.57132151e-01 -4.13499086e-01
  -1.02337457e-01 -3.57132151e-01  4.13499086e-01  4.59705219e-02]
 [ 1.66666667e-01  1.15733411e-16 -3.16227766e-01  5.00000000e-01
  -4.01645547e-01 -5.701927

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 12)