In [18]:
# Calculate singular value decomposition of a matrix
mat = [
    [-1, 1, 0, 0],
    [0, -1, 1, 0],
    [0, 0, -1, 1],
    [1, 0, 0, -1],
]

# Make a larger matrix similar to this but 256 by 256
# The diagonal should be (-1, 1), (-1, 1), (-1, 1), (-1, 1), ...
# The rest of the matrix should be zeros

# mat = np.zeros((256, 256))
# for i in range(256):
#     mat[i, i] = -1
#     mat[i, (i + 1) % 256] = 1

len = 5
# len = 512
mat = np.zeros((len * 3, len))
for i in range(len):
    mat[i, i] = 1
for i in range(len):
    mat[i + len, i] = -1
    # mat[i + len, (i + 1) % len] = 1
    mat[(i + 1) % len + len, i] = 1
for i in range(len):
    mat[i + len * 2, i] = -1
    # mat[(i + 1) % len + len * 2, i] = 1
    mat[i + len * 2, (i + 1) % len] = 1
    
    
if len <= 6:
    print(f"Matrix of size {len * 2} by {len}:")
    print(mat)
    print()

# Find norm-1 of the matrix
print("Norm-1 of the matrix:")
print(np.linalg.norm(mat, 1))
print()

print("Norm-2 of the matrix:")
print(np.linalg.norm(mat, 2))
print()


import numpy as np
u, s, vh = np.linalg.svd(mat)

print("U:")
print(u)
print()

print("S:")
print(s)
print()

print("VH:")
print(vh)
print()

print("Reconstructed matrix:")
print(u @ np.diag(s) @ vh)
print()



Matrix of size 10 by 5:
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [-1.  0.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.]
 [-1.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0. -1.  1.  0.]
 [ 0.  0.  0. -1.  1.]
 [ 1.  0.  0.  0. -1.]]

Norm-1 of the matrix:
5.0

Norm-2 of the matrix:
2.8698550446842765

U:
[[ 6.46441391e-17 -2.20378912e-01  3.25993627e-01 -5.55631336e-18
   4.47213595e-01  3.86626484e-01 -4.09573310e-01 -3.95581514e-02
   9.86773567e-04  6.15182035e-02  4.09573310e-01  3.95581514e-02
  -9.86773567e-04 -6.15182035e-02 -3.86626484e-01]
 [ 1.29535474e-01  1.78290285e-01  1.00737571e-01  3.10038363e-01
   4.47213595e-01  8.86158921e-02  3.62839019e-01 -4.26026480e-01
  -3.77526996e-02  1.23242688e-02 -3.62839019e-01  4.26026480e-01
   3.77526996e-02 -1.23242688e-02 -8.86158921e-02]
 [-2.09592800e-01 -6.81008290e-02 -2.63734384e-01  1.916142

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 15)