In [4]:
!python -m unittest

sigma_np = 0.44113463163375854
img_noisy = 
[[1 2 3]
 [4 3 5]
 [9 7 9]]
.UNet output shape: torch.Size([1, 2, 512, 512, 1])
Conv3d output shape: torch.Size([1, 64, 512, 512, 1])
DoubleConv output shape: torch.Size([1, 128, 512, 512, 1])
MaxPool3d output 1 shape: torch.Size([1, 1, 256, 256, 1])
MaxPool3d output 2 shape: torch.Size([1, 128, 256, 256, 1])
ConvTranspose3d output shape: torch.Size([1, 512, 64, 64, 1])
Upsample output shape: torch.Size([1, 1, 1024, 1024, 1])
.
----------------------------------------------------------------------
Ran 2 tests in 1.265s

OK


In [1]:
import unittest
unittest.main(argv=[''], exit=False)
# unittest.main()


----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
