In [13]:
import torch
import doctest


In [14]:
import torch

def forward_difference_x(u, dx):
    """
    Compute the forward finite difference in the x direction.
    
    Args:
    u (torch.Tensor): Input 2D tensor.
    dx (float): Grid spacing in the x direction.

    Returns:
    torch.Tensor: Forward finite difference in the x direction with the same dimensions as the input.
    
    Example:
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> dx = 1.0
    >>> forward_difference_x(u, dx)
    tensor([[ 3.,  3.,  3.],
            [ 3.,  3.,  3.],
            [-7., -8., -9.]])
    """
    diff_x = torch.diff(u, dim=0, append=torch.zeros_like(u[0:1, :])) / dx
    diff_x[-1, :] = -u[-1, :] / dx
    return diff_x

def forward_difference_y(u, dy):
    """
    Compute the forward finite difference in the y direction.
    
    Args:
    u (torch.Tensor): Input 2D tensor.
    dy (float): Grid spacing in the y direction.

    Returns:
    torch.Tensor: Forward finite difference in the y direction with the same dimensions as the input.
    
    Example:
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> dy = 1.0
    >>> forward_difference_y(u, dy)
    tensor([[ 1.,  1., -3.],
            [ 1.,  1., -6.],
            [ 1.,  1., -9.]])
    """
    diff_y = torch.diff(u, dim=1, append=torch.zeros_like(u[:, 0:1])) / dy
    diff_y[:, -1] = -u[:, -1] / dy
    return diff_y

def backward_difference_x(u, dx):
    """
    Compute the backward finite difference in the x direction.
    
    Args:
    u (torch.Tensor): Input 2D tensor.
    dx (float): Grid spacing in the x direction.

    Returns:
    torch.Tensor: Backward finite difference in the x direction with the same dimensions as the input.
    
    Example:
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> dx = 1.0
    >>> backward_difference_x(u, dx)
    tensor([[1., 2., 3.],
            [3., 3., 3.],
            [3., 3., 3.]])
    """
    diff_x = torch.diff(u, dim=0, prepend=torch.zeros_like(u[0:1, :])) / dx
    diff_x[0, :] = u[0, :] / dx
    return diff_x

def backward_difference_y(u, dy):
    """
    Compute the backward finite difference in the y direction.
    
    Args:
    u (torch.Tensor): Input 2D tensor.
    dy (float): Grid spacing in the y direction.

    Returns:
    torch.Tensor: Backward finite difference in the y direction with the same dimensions as the input.
    
    Example:
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> dy = 1.0
    >>> backward_difference_y(u, dy)
    tensor([[1., 1., 1.],
            [4., 1., 1.],
            [7., 1., 1.]])
    """
    diff_y = torch.diff(u, dim=1, prepend=torch.zeros_like(u[:, 0:1])) / dy
    diff_y[:, 0] = u[:, 0] / dy
    return diff_y

def test_adjoint_property():
    """
    Test the adjoint property of forward and backward difference operators.
    """
    dx = 1.0
    dy = 1.0

    # Define two random 2D tensors
    u = torch.rand((5, 5), dtype=torch.float32)
    v = torch.rand((5, 5), dtype=torch.float32)

    # Compute forward differences
    Df_x_u = forward_difference_x(u, dx)
    Df_y_u = forward_difference_y(u, dy)

    # Compute backward differences
    Db_x_v = backward_difference_x(v, dx)
    Db_y_v = backward_difference_y(v, dy)

    # Compute inner products
    inner_product_x = torch.sum(Df_x_u * v)
    inner_product_y = torch.sum(Df_y_u * v)

    adjoint_product_x = -torch.sum(u * Db_x_v)
    adjoint_product_y = -torch.sum(u * Db_y_v)

    # Check if they are approximately equal
    assert torch.allclose(inner_product_x, adjoint_product_x, atol=1e-6), f"X-direction: {inner_product_x} != {adjoint_product_x}"
    assert torch.allclose(inner_product_y, adjoint_product_y, atol=1e-6), f"Y-direction: {inner_product_y} != {adjoint_product_y}"
    
    print(f"Test adjoint property successful!")

if __name__ == "__main__":
    import doctest
    doctest.testmod()

    # Test with the given example
    u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    dx = 1.0
    dy = 1.0

    print("X forward difference:")
    print(forward_difference_x(u, dx))

    print("X backward difference:")
    print(backward_difference_x(u, dx))

    print("Y forward difference:")
    print(forward_difference_y(u, dy))

    print("Y backward difference:")
    print(backward_difference_y(u, dy))


X forward difference:
tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [-7., -8., -9.]])
X backward difference:
tensor([[1., 2., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
Y forward difference:
tensor([[ 1.,  1., -3.],
        [ 1.,  1., -6.],
        [ 1.,  1., -9.]])
Y backward difference:
tensor([[1., 1., 1.],
        [4., 1., 1.],
        [7., 1., 1.]])


In [15]:
doctest.testmod()
test_adjoint_property()

Test adjoint property successful!
