In [15]:
import torch

def forward_difference_x(u):
    """
    Computes the forward difference in the x direction.
    
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> forward_difference_x(u)
    tensor([[3., 3., 3.],
            [3., 3., 3.],
            [0., 0., 0.]])
    """
    N1, N2 = u.shape
    diff_x = torch.zeros_like(u)
    diff_x[:-1, :] = u[1:, :] - u[:-1, :]
    return diff_x

def forward_difference_y(u):
    """
    Computes the forward difference in the y direction.
    
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> forward_difference_y(u)
    tensor([[1., 1., 0.],
            [1., 1., 0.],
            [1., 1., 0.]])
    """
    N1, N2 = u.shape
    diff_y = torch.zeros_like(u)
    diff_y[:, :-1] = u[:, 1:] - u[:, :-1]
    return diff_y

def backward_difference_x(u):
    """
    Computes the backward difference in the x direction.
    
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> backward_difference_x(u)
    tensor([[ 1.,  2.,  3.],
            [ 3.,  3.,  3.],
            [-4., -5., -6.]])
    """
    N1, N2 = u.shape
    diff_x = torch.zeros_like(u)
    diff_x[0, :] = u[0, :]
    diff_x[1:-1, :] = u[1:-1, :] - u[:-2, :]
    diff_x[-1, :] = -u[-2, :]
    return diff_x

def backward_difference_y(u):
    """
    Computes the backward difference in the y direction.
    
    >>> u = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    >>> backward_difference_y(u)
    tensor([[ 1.,  1., -2.],
            [ 4.,  1., -5.],
            [ 7.,  1., -8.]])
    """
    N1, N2 = u.shape
    diff_y = torch.zeros_like(u)
    diff_y[:, 0] = u[:, 0]
    diff_y[:, 1:-1] = u[:, 1:-1] - u[:, :-2]
    diff_y[:, -1] = -u[:, -2]
    return diff_y

def test_adjoint_property():
    """
    Test the adjoint property for forward and backward difference operators.
    
    >>> adjoint_x, adjoint_y = test_adjoint_property()
    >>> assert abs(adjoint_x) < 1e-6, f"Adjoint property failed for x: {adjoint_x}"
    >>> assert abs(adjoint_y) < 1e-6, f"Adjoint property failed for y: {adjoint_y}"
    """
    N1, N2 = 4, 4  # Example dimensions
    u = torch.rand((N1, N2))
    v = torch.rand((N1, N2))

    fwd_x_u = forward_difference_x(u)
    bwd_x_v = backward_difference_x(v)
    adjoint_x = torch.sum(fwd_x_u * v) + torch.sum(u * bwd_x_v)
    
    fwd_y_u = forward_difference_y(u)
    bwd_y_v = backward_difference_y(v)
    adjoint_y = torch.sum(fwd_y_u * v) + torch.sum(u * bwd_y_v)
    
    return adjoint_x.item(), adjoint_y.item()

if __name__ == "__main__":
    import doctest
    doctest.testmod()
    print("Adjoint property test results:", test_adjoint_property())


Adjoint property test results: (-1.1920928955078125e-07, -1.1920928955078125e-07)


In [16]:
def test_adjoint_property():
    """
    Test the adjoint property of forward and backward difference operators.
    """
    dx = 1.0
    dy = 1.0

    # Define two random 2D tensors
    u = torch.rand((5, 5), dtype=torch.float32)
    v = torch.rand((5, 5), dtype=torch.float32)

    # Compute forward differences
    Df_x_u = forward_difference_x(u)
    Df_y_u = forward_difference_y(u)

    # Compute backward differences
    Db_x_v = backward_difference_x(v)
    Db_y_v = backward_difference_y(v)

    # Compute inner products
    inner_product_x = torch.sum(Df_x_u * v)
    inner_product_y = torch.sum(Df_y_u * v)

    adjoint_product_x = -torch.sum(u * Db_x_v)
    adjoint_product_y = -torch.sum(u * Db_y_v)

    # Check if they are approximately equal
    assert torch.allclose(inner_product_x, adjoint_product_x, atol=1e-6), f"X-direction: {inner_product_x} != {adjoint_product_x}"
    assert torch.allclose(inner_product_y, adjoint_product_y, atol=1e-6), f"Y-direction: {inner_product_y} != {adjoint_product_y}"
    
    print(f"Test adjoint property successful!")

In [17]:
test_adjoint_property()

Test adjoint property successful!
